<?php
/**
 * CRICRI — biblioteca de prompts de QUADRO (extraída dos motores Malta, 08/07/2026).
 * Cada item vira uma opção "Estilo do quadro" no editor: o texto é o prompt img2img
 * completo (rosto da foto de referência → arte pintada). Blocos repetidos ficam em
 * variáveis pra não duplicar. Retorna array de {id, grupo, nome, texto}.
 */

// ---- blocos compartilhados (api/_prompt.php) ----
$FRAMING = <<<'T'
FRAMING (critical): keep exactly the same framing, zoom level and composition as the reference photo. Include the FULL subject or subjects exactly as shown, with the same headroom and side margins as the reference. Do NOT crop, do NOT zoom in, and never cut off any part of any subject — the entire head, hair and body that appear in the reference must stay fully visible inside the frame.
T;
$BG = <<<'T'
BACKGROUND (critical): output ONE fully-painted, fully OPAQUE image that fills the entire frame edge to edge — a complete painted scene behind the subject. NEVER output a transparent background, an alpha cutout, an isolated/floating subject, or a plain flat (white, black or solid-colour) background. Every single pixel must be part of the painting.
T;
$FACE = <<<'T'
THE FACE IS SACRED — photographic likeness above all. Treat this as a faithful portrait commission of the photographed people, not a reinterpretation. Reproduce each face with the precise, photorealistic accuracy of the reference: the exact same face shape, bone structure, jawline, cheekbones, eye shape and color, eyebrows, exact nose, exact lips and mouth width, hairline, skin tone, age lines and every distinctive feature (freckles, moles, scars, facial hair, glasses). The face must read as the REAL person photographed — only with a thin, refined painterly finish on top. Do NOT stylize, caricature, exaggerate, smooth, slim, beautify, youthen or idealize the features. Keep the asymmetries and real proportions exactly; if in doubt, stay closer to the photograph.
T;
$PROPS = <<<'T'
PROPORTIONS & IDENTITY LOCK (critical): keep each subject's exact head size, head-to-shoulder ratio, neck length and overall body proportions exactly as in the reference — do not enlarge the eyes, shrink the nose, narrow the face, elongate the neck or resize any head relative to its body. Preserve each subject's exact gaze direction, head tilt and facial expression. Keep each subject's hairstyle, hair length, hair color and parting recognizably the same as the photo — render the hair in oil-paint texture, but NEVER restyle it into a period wig, updo or different cut.
T;
$KID = "The subject is a CHILD: preserve the exact age — never age up, mature or adultize the child's features; keep the authentic childlike proportions, round cheeks and eyes exactly as photographed.";
$FACE_PET = <<<'T'
THE PET'S FACE IS SACRED — photographic likeness above all. Reproduce the pet with the precise, photorealistic accuracy of the reference: the exact same muzzle shape and length, ear shape and carriage, eye shape and color, nose shape and color, whisker placement, fur color, fur length and texture, coat pattern and every marking, patch or spot visible in the photo. The animal must read as the REAL pet photographed — instantly recognizable to its owner. Do NOT cartoonify, humanize the face, alter the breed's features, change proportions or idealize the animal.
T;
$CLOTHING_FUT = <<<'T'
CLOTHING LOCK (critical): keep the EXACT clothing and football jersey from the reference photo — its real colors, stripes, collar and sleeves. Do NOT add, invent, redesign or remove any crest, badge, logo or sponsor text; if a crest is visible in the photo, render it only as a soft painterly suggestion of what is actually there. Never replace the shirt with a different team's design.
T;

$lock = "\n\n$FRAMING\n\n$BG";

// helper
$i = 0;
$mk = function ($grupo, $nome, $texto) use (&$i) {
  return ['id' => 'qd_' . substr(md5($grupo . $nome), 0, 10), 'grupo' => $grupo, 'nome' => $nome, 'texto' => trim($texto)];
};

$Q = [];

// ===== / (clássico) =====
$g = 'Clássico (/)';
$Q[] = $mk($g, 'Óleo Impressionista', <<<T
Using the attached reference photo as the exact subject, paint a faithful impressionistic oil portrait of the same subject or subjects shown — whether one person, a couple, a family, a child, or a pet. If the photo contains more than one subject, include and preserve every one of them, in the same arrangement and number as the reference.

Preserve the precise likeness of each subject: keep the identical face shape, bone structure, eye shape and color, nose, lips, eyebrows, hairline, hair color and texture, skin tone, age and body proportions, plus every distinctive feature. Apply the artistic style ON TOP of the real photo, never replacing or idealizing them.

Render in expressive impasto oil technique with thick, visible palette-knife strokes and chunky paint texture on a coarse canvas weave. Bold blocky brushwork, patches of color laid side by side. Skin and fur tones stay realistic, juxtaposed with earthy ochres, warm terracotta oranges and deep dramatic blues, accented by stark white highlights. Strong cinematic chiaroscuro — directional warm light from one side, deep shadows, a soulful Rembrandt presence. Keep the natural pose and expression of the reference intact.

Final image: fine art gallery quality, hyper-detailed paint layers, visible canvas weave texture.$lock
T);
$Q[] = $mk($g, 'Realeza (séc. XVIII)', "$FACE\n\n$PROPS\n\nUsing the attached reference photo, paint a museum-quality 18th-century European Old Master oil portrait — the subject reimagined as European aristocracy in the Grand Manner of Gainsborough, Reynolds and Lawrence. Dress and stage the subject as nobility from the neck DOWN only: rich garments in deep crimson and burgundy velvet, midnight-blue and emerald silk, cream and ivory brocade, delicate white lace collars and cuffs, gold embroidery and pearl jewelry. Keep the original pose; regal dignity comes from costume, lighting and setting. Authentic Old Master oil technique: refined restrained brushwork, soft fine blending on the skin, looser strokes in clothing and background, luminous glazed layers, deep velvety shadows, aged-varnish patina, visible fine canvas weave. Warm low-key Rembrandt lighting. Background: a deep dark draped velvet curtain or a romantic dusky landscape — never modern, oil-painted edge to edge.$lock");
$Q[] = $mk($g, 'Van Gogh (Noite Estrelada)', "Using the attached reference photo, create a single unified Vincent van Gogh oil painting placing the same subject(s) in the foreground against a faithful recreation of Van Gogh's The Starry Night (1889). Preserve every subject in the same arrangement and number. THE BACKGROUND must be faithful to the original: turbulent night sky with the large swirling double-spiral vortex, a bright crescent moon in a luminous halo upper-right, radiant halo-ringed stars, rolling swirling brushstrokes of cobalt and ultramarine, the dark hills, small village with church steeple and flame-like cypress. THE SUBJECT(S) fully painted in Van Gogh's hand — visible impasto strokes shaping every feature, skin in layered ochres and siennas with cool shadows, outlines reinforced with darker paint — preserving each recognizable likeness through painted form. ONE single painting, the same brushstroke energy and impasto texture edge to edge.$lock");
$Q[] = $mk($g, 'Pixar 3D', "Using the attached reference photo, render a faithful Pixar-style 3D animated portrait of the same subject(s). Preserve the likeness translated into the Pixar aesthetic: same face shape, eye shape and color, nose, lips, hairline, hair, skin tone, age and proportions, every distinctive feature — instantly recognizable, style ON TOP of real features. Signature Pixar CG: slightly enlarged expressive eyes, nuanced subsurface skin shading, softly exaggerated appealing proportions, fine pore and hair detail, fabric weave, vibrant grounded colors, warm cinematic three-point studio lighting. Keep the natural pose and expression. Feature-film quality, ultra-detailed CG.$lock");

// ===== /crianca =====
$g = 'Criança';
$Q[] = $mk($g, 'Óleo Clássico (criança)', "$FACE\n\n$PROPS $KID\n\nUsing the attached reference photo, paint a museum-quality classic oil portrait of the same child or children — timeless, tender, an heirloom for the family home. Keep the child's clothing essentially as photographed in soft oil-paint texture. Keep the exact pose and expression, including spontaneous smiles and dimples. Refined Old Master oil technique softened for childhood: delicate blending on the face with warmth and light, looser strokes in clothing and background, luminous glazes, soft shadows, subtle canvas weave. Warm embracing key light. Background: a soft warm gradient of cream, umber and a whisper of dusty blue — quiet and timeless, oil-painted edge to edge.$lock");
$Q[] = $mk($g, 'Principezinho (Velázquez)', "$FACE\n\n$PROPS $KID\n\nUsing the attached reference photo, paint a museum-quality royal court portrait of the same child in the manner of Velázquez's infantas — dignified, tender. Dress the child as young royalty from the neck DOWN only: an ornate court dress or princely doublet in cream, soft rose or deep blue silk with delicate lace trim, subtle gold embroidery and a small ribbon — scaled truthfully to the child's age, elegant, never costume-y. Spanish Golden Age oil technique: soft loving blending on the face, fluid strokes in the silks and lace, luminous glazes, deep warm shadows, aged patina. Background: a soft palace interior suggestion, atmospheric and quiet so the child glows.$lock");
$Q[] = $mk($g, 'Conto de Fadas (aquarela)', "$FACE\n\n$PROPS $KID\n\nUsing the attached reference photo, create a classic EUROPEAN STORYBOOK illustration of the same child — a page from a beautiful old fairy-tale book in fine watercolor and gouache. Soft layered watercolor washes, delicate gouache highlights, a fine warm ink contour line, gentle paper texture. Explicitly NOT 3D, NOT a cartoon, NOT any animation studio's look. Dress the child in gentle fairy-tale clothing from the neck down — a simple cape, soft princess dress or woodland clothes in warm muted tones. Background: an enchanted generic fairy-tale scene — a soft watercolor forest clearing with fireflies, or a distant castle under a warm sky — dreamy, with visible paper grain, illustrated edge to edge.$lock");

// ===== /familia =====
$g = 'Família';
$Q[] = $mk($g, 'Óleo Clássico (família)', "$FACE\n\n$PROPS\n\nUsing the attached reference photo, paint a museum-quality classic family oil portrait — preserving every person in the same arrangement, relative heights, embraces and number as the reference; never add or remove anyone. Keep everyone's clothing essentially as photographed in noble oil-paint texture. Refined Old Master oil technique: soft blending on every face so each likeness stays true, looser strokes in clothing, hair and background, luminous glazes, deep velvety shadows, aged patina, fine canvas weave. Warm Rembrandt lighting embracing the whole group. Background: a warm timeless domestic-classical interior — soft dark wood tones, a hint of drapery — intimate and atemporal, oil-painted edge to edge.$lock");
$Q[] = $mk($g, 'Realeza (família)', "$FACE\n\n$PROPS\n\nUsing the attached reference photo, paint a museum-quality 18th-century Old Master FAMILY portrait — the same people reimagined as an aristocratic family in the Grand Manner. Preserve every member in the same arrangement, relative heights and number. Dress and stage the family as nobility from the neck DOWN only: deep crimson and burgundy velvet, midnight-blue and emerald silk, cream brocade, lace collars and cuffs, gold embroidery and pearls; children in period dress scaled to their age. Keep everyone's original pose. Authentic Old Master oil technique, luminous glazes, deep shadows, aged patina, fine canvas weave, warm low-key Rembrandt lighting. Background: a stately classical setting — draped velvet curtain with a glimpse of a dusky estate landscape.$lock");
$Q[] = $mk($g, 'Renascença (família)', "$FACE\n\n$PROPS\n\nUsing the attached reference photo, paint a museum-quality High Renaissance family portrait in the manner of Raphael and Titian — preserving every person in the same arrangement, relative heights and number. Dress the family in understated Renaissance garments from the neck down — soft draped fabrics in warm earth tones, muted jewel reds and deep greens. Keep everyone's original pose and expression. Delicate sfumato modeling on the faces (soft smoky transitions, no hard edges), luminous layered glazes, balanced serene composition, warm golden Italian light from one side, fine canvas texture with age patina. Background: a soft atmospheric Tuscan landscape — distant rolling hills, cypress silhouettes, a hazy golden sky with aerial perspective.$lock");

// ===== /pet =====
$g = 'Pet';
$Q[] = $mk($g, 'Óleo Clássico (pet)', "$FACE_PET\n\nUsing the attached reference photo, paint a museum-quality classic oil portrait of the SAME PET — natural and dignified, NO costume, no props: just the animal elevated by masterful painting. PROPORTIONS LOCK: keep the pet's exact head size, head-to-body ratio and anatomy; preserve the exact gaze, head tilt and expression (an open mouth or visible tongue stays exactly as photographed). Authentic Old Master oil technique: soft refined blending on the face and eyes so the gaze stays alive, fur built from layered directional strokes following the real coat's growth, luminous glazes, deep velvety shadows, aged patina, fine canvas weave. Warm low-key Rembrandt lighting with a gentle catchlight in each eye. Background: a deep dark atmospheric backdrop — soft umber and near-black with a faint warm glow behind the head.$lock");
$Q[] = $mk($g, 'Pet Nobre (aristocracia)', "$FACE_PET\n\nUsing the attached reference photo, paint a museum-quality 18th-century Old Master oil portrait of the SAME PET reimagined as European aristocracy — a noble animal of title and estate. PROPORTIONS LOCK: keep exact head size, head-to-body ratio and anatomy; preserve exact gaze and expression. Dress the pet as nobility from the neck DOWN only: a rich velvet coat in deep crimson or midnight blue over the shoulders, a delicate white lace ruff, a single gold brooch — tailored naturally around the pet's real body, dignified, never costume-party silly. Authentic Old Master oil technique, soft blending on the face with individually suggested fur strokes, luminous glazes, deep shadows, aged patina. Background: a classical setting — deep dark velvet curtain or a dim stately study with a hint of gilt.$lock");
$Q[] = $mk($g, 'Pet General (uniforme de gala)', "$FACE_PET\n\nUsing the attached reference photo, paint a museum-quality 19th-century military gala oil portrait of the SAME PET — a distinguished general in ceremonial dress uniform, painted with complete seriousness. PROPORTIONS LOCK: keep exact head size, head-to-body ratio and anatomy; preserve exact gaze and expression. Dress the pet from the neck DOWN in an ornate ceremonial gala uniform: a dark dress coat with gold epaulettes, braided aiguillettes, a sash of honor and a few ceremonial medals — ALL heraldry and insignia GENERIC and invented, never real-world. Authentic Old Master oil technique, gleaming highlights on the gold braid, luminous glazes, deep shadows, aged patina. Background: a dim official study or dark velvet curtain with a faint globe or map table.$lock");

// ===== /religiao =====
$g = 'Fé (devocional)';
$fe_rule = "SETTING RULE: do NOT add halos, crosses, rosaries, saints, angels or any religious symbol not present in the reference — the sacred quality lives entirely in the LIGHT, the serenity and the painterly atmosphere.";
$Q[] = $mk($g, 'Luz Sagrada (Rembrandt)', "$FACE\n\n$PROPS\n\n$fe_rule\n\nUsing the attached reference photo, paint a museum-quality devotional oil portrait in the sacred-light tradition of Rembrandt — serene, reverent, contemplative. Keep the clothing essentially as photographed in soft oil-paint with muted humble tones. Keep the exact pose and expression. Authentic Old Master oil technique, soft blending on the face, luminous layered glazes, deep shadows, aged patina, fine canvas weave. THE LIGHT IS THE SOUL: a single soft beam falling from high above — like light through a high window — gently bathing the face and shoulders out of a deep warm darkness with tenderness and peace. Background: a deep quiet warm darkness with a faint glow where the light falls.$lock");
$Q[] = $mk($g, 'Renascença Sacra', "$FACE\n\n$PROPS\n\n$fe_rule\n\nUsing the attached reference photo, paint a museum-quality Renaissance devotional portrait in the serene sacred-art language of the Italian masters — peaceful, luminous, full of grace. Drape the clothing in soft classical Renaissance folds from the neck down — humble tones of deep blue, wine red and warm cream. Keep the exact pose and expression. Delicate sfumato on the face, luminous golden glazes layered like candlelight, serene balanced composition, fine canvas texture with age patina. Background: a soft golden radiance — a warm glowing gradient like aged gold leaf, faintest suggestion of classical architecture dissolving into light, sacred without any symbol.$lock");
$Q[] = $mk($g, 'Vitral (cathedral glass)', "$FACE\n\n$PROPS\n\n$fe_rule The window's ornamental border must be neutral geometric or floral motifs only.\n\nUsing the attached reference photo, create a luminous stained-glass artwork of the same subject(s) — a cathedral window portrait glowing with transmitted light. Give the face its own larger clearer glass panels with finer sparser lead lines so the true likeness reads perfectly; bolder leading and richer mosaic belong in clothing and background. Authentic leaded stained glass: panels of luminous cathedral glass in deep jewel tones — ruby, sapphire, amber, emerald, violet — separated by dark lead came lines, light streaming through from behind so every piece glows; subtle glass texture, bubbles, grisaille shading on the face. Background: radiant panels in warm golds and deep blues with a neutral ornamental geometric border, glowing edge to edge.$lock");

// ===== /futebol (retrato pintado) =====
$g = 'Futebol (retrato)';
$Q[] = $mk($g, 'Herói (óleo épico)', "$FACE\n\n$PROPS\n\n$CLOTHING_FUT\n\nUsing the attached reference photo, paint a museum-quality EPIC oil portrait — a football devotee immortalized like a hero of the game, in dramatic classical oil technique. Cinematic Old Master oil: refined blending on the face, bolder strokes in the clothing and atmosphere, luminous glazes and deep shadows on fine canvas weave. Dramatic chiaroscuro: cool-white stadium floodlight glow rims the figure from behind while a warm key light models the face — heroic, intense, dignified. Background: a GENERIC football stadium at dusk, soft and out of focus — anonymous floodlight towers flaring, a blurred crowd in dabs of paint, a deep teal-and-amber sky; no readable banners, no real architecture, no legible text.$lock");
$Q[] = $mk($g, 'Lenda (litografia anos 50)', "$FACE\n\n$PROPS\n\n$CLOTHING_FUT\n\nUsing the attached reference photo, create a vintage 1950s sports lithograph poster illustration — a golden-age football legend in the warm retro print style of mid-century athletic posters. Limited retro palette (warm cream paper base, muted vermilion, ochre, teal and navy), soft visible print grain and halftone texture, confident simplified shading that keeps the face accurate, slight ink misregistration charm. Keep the pose exactly as photographed. Absolutely NO typography, lettering, numbers or text anywhere. Background: a simplified retro stadium suggestion or radiating vintage sunburst in aged poster tones, paper texture across the whole image.$lock");
$Q[] = $mk($g, 'Óleo Nobre (camisa do time)', "$FACE\n\n$PROPS\n\n$CLOTHING_FUT\n\nUsing the attached reference photo, paint a museum-quality formal Old Master oil portrait — the full classical treatment of an 18th-century nobleman's portrait, except the sitter proudly wears their real football shirt from the photo. The contrast IS the concept: museum solemnity meets the terraces. Authentic Old Master oil technique: refined blending on the skin, looser strokes on the jersey fabric (painted lovingly like royal silk), luminous glazes, deep velvety shadows, aged patina, fine canvas weave. Warm low-key Rembrandt lighting. Background: a deep dark draped velvet curtain or moody gradient studio backdrop — formal, solemn, timeless.$lock");

// ===== /pinturapai =====
$g = 'Pinturapai (Dia dos Pais)';
$pai_base = function ($style) {
  return "Create a portrait artwork based on the attached reference photo.\n\nTHE FACE IS SACRED — photographic likeness above all. The reference photo is the absolute source of truth: preserve EVERY person's exact facial features, skin tone, hair, beard and moustache density, apparent age and expression with total precision. Do NOT straighten curly or coily hair and do NOT change its texture. Add no facial hair that is not in the photo. Keep ONLY the accessories visible in the photo; if there are none, add none. If more than one person appears, render ALL of them together, each unmistakably themselves.\n\nSTYLE: $style\n\nCOMPOSITION: vertical portrait framing. The subject's head and shoulders — and the full group, if more than one — sit comfortably inside the frame, centered, with gentle margins. Never crop a face.\n\nNO TEXT: do NOT write any words, names, letters, signatures, captions or numbers anywhere.\n\nBACKGROUND LOCK: output ONE fully OPAQUE image that fills the entire frame edge to edge. NEVER a transparent background, an alpha cutout, a floating subject, or a flat solid-colour background.\n\nNO PICTURE FRAME: do NOT add any decorative picture frame, gilded border, mat or vignette. The artwork itself reaches all four edges.";
};
$Q[] = $mk($g, 'Óleo Clássico', $pai_base('a warm, timeless classical OIL PAINTING portrait in the tradition of the old masters — visible expressive oil brushstrokes and gentle impasto, soft Rembrandt-like warm directional lighting (chiaroscuro), a deep muted painterly background of warm browns, deep greens and soft golden bokeh. Dignified, intimate and heirloom-like.'));
$Q[] = $mk($g, 'Pintura de Rei', $pai_base('a grand RENAISSANCE-style royal STATE PORTRAIT — the subject painted with the full dignity of a monarch: elegant refined regal dark attire with subtle gold and deep-tone detailing (noble and tasteful, NEVER a cheap costume), dramatic classical oil lighting, an opulent palace-like dark background with soft draped curtains. Baroque grandeur, noble and powerful.'));
$Q[] = $mk($g, 'Carvão P&B', $pai_base('a refined CHARCOAL AND GRAPHITE portrait on textured fine-art paper — elegant black-and-white, expressive hand-drawn shading and contour, soft smudging with luminous highlights, a quiet sober emotional gallery-drawing feel. Intimate and masterful.'));
$Q[] = $mk($g, 'Caricatura', $pai_base('a fun, affectionate professional CARICATURE illustration — proportions playfully exaggerated (a slightly larger head and lively expressive features) while keeping him instantly and warmly recognizable; clean modern digital cartoon line-and-colour, bright and cheerful, a simple light studio background. Charming and good-humoured, never grotesque.'));
$Q[] = $mk($g, 'Herói Aranha', $pai_base('a bold fun cinematic SUPERHERO scene — the person wearing a sleek spider-themed superhero suit (red and deep blue with a subtle web texture, generic, no real logo), in a confident heroic pose on a city rooftop at golden dusk. IMPORTANT: his face is FULLY VISIBLE with NO mask covering it — unmistakably him. Comic-movie energy, epic and playful.'));
$Q[] = $mk($g, 'Super-Herói', $pai_base('a triumphant fun cinematic SUPERHERO scene — the person as a classic caped hero: a blue suit with a flowing red cape and a bold generic chest emblem (no real logo), standing proud and strong with wind in the cape and a bright sky behind. His face is fully visible and unmistakably him. Uplifting, heroic and playful.'));

// ===== /signo (12 signos) =====
$g = 'Signo (Retrato Astral)';
$signo_base = function ($sign_en, $scene) {
  return "Generate a breathtaking, museum-grade celestial portrait of the person in the attached reference photo, reimagined as the divine embodiment of their zodiac sign — $sign_en.\n\nTHE FACE IS SACRED — photographic likeness above all. Preserve the person's exact facial features, face shape, skin tone, eye colour and hair with total precision. Do NOT straighten curly or coily hair. Beard and moustache density IDENTICAL to the photo — add no facial hair not in the reference. Keep ONLY accessories visible in the photo. Do NOT slim, age, lighten or beautify the face — it must be unmistakably the real person.\n\nPORTRAIT: head-and-shoulders, the person facing the viewer with a serene powerful presence, adorned and placed within the world below.\n\nWORLD: $scene\n\nThe delicate star-constellation of $sign_en is traced subtly in faint starlight in the background. NO text, names, letters, numbers, logos or watermarks anywhere.\n\nRENDERING: a luminous blend of fine-art painterly richness and photoreal detail — cinematic lighting, soft glowing rim light on the face, deep atmospheric background, intricate and premium.\n\nCOMPOSITION: vertical 3:4 portrait framing, head and shoulders fully visible, centered, comfortable margins — never cropped at the top of the head.\n\nBACKGROUND LOCK: output ONE fully OPAQUE image edge to edge — never transparent, an alpha cutout, a floating subject or a flat solid-colour background.\n\nNO PICTURE FRAME: no decorative frame, gilded border, mat or vignette. The artwork reaches all four edges.";
};
$signs = [
  ['Áries', 'Aries the Ram', 'The world of Aries the Ram: the person wears luminous forged-bronze armor with subtle ram-horn detailing at the shoulders, glowing embers and sparks drifting, a fiery dawn breaking behind. Palette of molten crimson, ember orange and burnished bronze. Mood: fearless, pioneering, ablaze with raw vitality.'],
  ['Touro', 'Taurus the Bull', 'The world of Taurus the Bull: the person crowned with golden wheat and emerald laurels, in a lush opulent garden at golden hour, a powerful bull silhouette resting in the soft distance. Palette of deep emerald, antique gold and warm terracotta. Mood: grounded, sensual, serenely abundant.'],
  ['Gêmeos', 'Gemini the Twins', 'The world of Gemini the Twins: the person amid a dual mirrored cosmos with swirling silver air currents and two luminous moons, a faint ethereal mirror-self shimmering at their side. Palette of liquid silver, violet and electric blue. Mood: curious, quicksilver, dazzling and dual.'],
  ['Câncer', 'Cancer the Moonchild', 'The world of Cancer the Moonchild: the person bathed in a soft lunar halo above a glassy moonlit tide, pearlescent waters and gentle silver mist, a delicate crab constellation glowing overhead. Palette of pearl, silver-blue and soft lilac. Mood: tender, intuitive, protective and luminous.'],
  ['Leão', 'Leo the Lion', 'The world of Leo the Sovereign Lion: the person wearing a radiant crown of solar light with a magnificent mane-like halo of golden flames, a regal golden cosmic savanna stretching behind. Palette of radiant gold, royal amber and sunfire. Mood: majestic, magnetic, born to command the room.'],
  ['Virgem', 'Virgo the Maiden', 'The world of Virgo the Maiden: the person amid a serene field of golden wheat and healing herbs beneath precise delicate constellations, holding a single softly glowing sheaf. Palette of sage green, wheat gold and ivory. Mood: pure, discerning, quietly powerful.'],
  ['Libra', 'Libra the Scales', 'The world of Libra: the person framed by perfectly balanced celestial golden scales and blooming roses within a symmetrical rose-gold cosmos. Palette of rose quartz, champagne gold and dusk pink. Mood: harmonious, elegant, effortlessly graceful.'],
  ['Escorpião', 'Scorpio the Phoenix', 'The world of Scorpio the Phoenix: the person emerging with an intense magnetic gaze from a deep crimson noir nebula and obsidian depths, embers of rebirth rising, a scorpion constellation burning above. Palette of deep crimson, obsidian black and blood-wine. Mood: intense, mysterious, transformative.'],
  ['Sagitário', 'Sagittarius the Archer', 'The world of Sagittarius the Archer: the person drawing a radiant bow of starlight toward a vast cosmic horizon, arrows of light streaking across a twilight sky. Palette of royal purple, gold and twilight indigo. Mood: adventurous, free, reaching for the infinite.'],
  ['Capricórnio', 'Capricorn the Sea-Goat', 'The world of Capricorn: the person standing composed and ancient on a starlit summit above a sea of clouds, an antique-gold sea-goat constellation arcing overhead. Palette of slate blue, charcoal and antique gold. Mood: timeless, disciplined, destined to rise.'],
  ['Aquário', 'Aquarius the Water-Bearer', 'The world of Aquarius the Visionary: the person amid futuristic cosmic currents and a shimmering aurora, pouring a stream of liquid stars from a luminous vessel. Palette of electric cyan, deep indigo and neon violet. Mood: visionary, electric, ahead of their time.'],
  ['Peixes', 'Pisces the Fish', 'The world of Pisces the Dreamer: the person submerged in a luminous oceanic dreamscape of bioluminescent waters, two fish of light circling them, soft iridescent mist. Palette of aquamarine, iridescent teal and soft violet. Mood: dreamy, ethereal, deeply soulful.'],
];
foreach ($signs as [$pt, $en, $scene]) $Q[] = $mk($g, $pt, $signo_base($en, $scene));

// ===== Bonecos colecionáveis (futebol / futebolbr / futebolkids) =====
// tipo 'boneco': a cena do avatar muda — segura o COLECIONÁVEL, não um quadro emoldurado.
$g = 'Boneco colecionável';
$bob_base = function ($figurine) {
  return "Generate a hyper-realistic studio photograph of a personalized miniature collectible bobblehead figurine, built from the attached reference photo.\n\nTHE FACE IS SACRED — photographic likeness above all. The reference photo is the absolute source of truth: preserve the person's exact facial features, skin tone and hair with total precision. Do NOT straighten curly or coily hair and do NOT change its texture. Beard and moustache density must be IDENTICAL to the photo — add no facial hair that is not in the reference. Keep ONLY the accessories visible in the photo (glasses, caps, earrings); if there are none, add none. The face must be instantly and unmistakably the real person.\n\n$figurine\n\nBASE: a two-layer base with a matte grass texture (no glossy reflections), clean with NO name and NO text engraved.\n\nBACKGROUND: a blurred football stadium during golden hour — warm amber sunset light, soft out-of-focus floodlights and a suggested crowd. No readable banners, no sponsor logos, no real stadium names and no legible text anywhere.\n\nRENDERING: hyper-realistic collectible product photography — sharp focus on the figurine and its base, soft golden stadium light, shallow depth of field, premium and lifelike, like a professional toy/figure product shot.\n\nCOMPOSITION: vertical portrait framing. The ENTIRE figurine and its full base must be visible inside the frame, centered, with comfortable margins — never cropped, never zoomed past the base.\n\nBACKGROUND LOCK: output ONE fully OPAQUE image that fills the entire frame edge to edge. NEVER output a transparent background, an alpha cutout, a floating/isolated subject, or a flat solid-colour background.\n\nNO PICTURE FRAME: do NOT add any decorative picture frame, gilded border, mat or vignette. The photograph itself reaches all four edges.";
};
$mkb = function ($nome, $texto) use ($g) {
  return ['id' => 'qd_' . substr(md5($g . $nome), 0, 10), 'grupo' => $g, 'nome' => $nome, 'tipo' => 'boneco', 'texto' => $texto];
};
$Q[] = $mkb('Boneco Copa (seleção · edite o kit)', $bob_base("FIGURINE: a classic sports bobblehead collectible (NOT a Funko Pop). The neck is short and thick — no spring, no coil, no spiral. The figurine wears the official home kit of a national football team: a bright yellow shirt with green trim, blue shorts and white socks. Render these kit colours and pattern EXACTLY — the uniform must be unmistakable. No sponsor logos, no brand marks and no readable text anywhere on the kit. It stands with one foot resting on a soccer ball."));
$Q[] = $mkb('Boneco Brasileirão (clube · edite o kit)', $bob_base("FIGURINE: a classic sports bobblehead collectible (NOT a Funko Pop). The neck is short and thick — no spring, no coil, no spiral. The figurine wears the home kit of a Brazilian football club: a football shirt with bold horizontal red and black hoops across the chest, white shorts and black socks. Render these kit colours and pattern EXACTLY. Show a small GENERIC embroidered crest shape on the left chest — an invented badge, NOT any real club's crest. No sponsor logos and no readable text anywhere on the kit. It stands with one foot resting on a soccer ball."));
$Q[] = $mkb('Boneco Futebol KIDS (criança · edite o kit)', $bob_base("THE PERSON IS A CHILD — keep the youthful child face exactly as in the photo. Do NOT age the child up or add any facial hair.\n\nFIGURINE: a classic sports bobblehead collectible of a CHILD football player (NOT a Funko Pop) — youthful child body proportions (a young kid, not an adult): shorter limbs, a rounder child physique, clearly a little boy or girl. The neck is short and thick — no spring, no coil, no spiral. The figurine wears the home kit of a Brazilian football club sized as a child's youth kit: a football shirt with bold horizontal red and black hoops across the chest, white shorts and black socks. Render these kit colours and pattern EXACTLY. Show a small GENERIC embroidered crest shape on the left chest — an invented badge, NOT any real club's crest. No sponsor logos and no readable text anywhere. It stands with one foot resting on a soccer ball."));

return $Q;
